name: test_dep

on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Check DEP
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            const data = fs.readFileSync('node_modules/@sharelist/webdav/package.json', 'utf8');
            yarn add @sharelist/webdav@0.1.5
            console.log(data)
            data = fs.readFileSync('node_modules/@sharelist/webdav/dist/index.js', 'utf8');
            console.log(data)
            const pk = require('@sharelist/webdav')
            console.log(pk)
